[package]
name = "at24cx"
version = "0.1.0"
authors = ["Diego Barrios Romero <eldruin@gmail.com>"]
repository = "https://github.com/eldruin/at24cx-rs"
license = "MIT OR Apache-2.0"
description = "Platform-agnostic Rust driver for the AT24CX series serial EEPROM."
readme = "README.md"
keywords = ["at24cx", "at24c32", "at24c64", "at24c256", "atmel", "driver", "eeprom", "embedded-hal-driver"]
categories = ["embedded", "hardware-support", "no-std"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
]

[features]
default = []

[dependencies]
embedded-hal = "0.2"

[dev-dependencies]
linux-embedded-hal = "0.2"
embedded-hal-mock = "0.2"

[profile.release]
lto = true
